# Generated by Django 5.2.11 on 2026-02-25 23:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/%Y/%m/%d/")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Processando"),
                            ("aguardando_revisao", "Aguardando Revisão"),
                            ("aprovado", "Aprovado"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("mensagem_erro", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DadosExtraidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chave_acesso", models.CharField(blank=True, max_length=44)),
                ("numero_nota", models.CharField(blank=True, max_length=20)),
                ("serie", models.CharField(blank=True, max_length=10)),
                ("cfop", models.CharField(blank=True, max_length=10)),
                ("data_emissao", models.DateField(blank=True, null=True)),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("nome_emitente", models.CharField(blank=True, max_length=255)),
                ("cnpj_emitente", models.CharField(blank=True, max_length=14)),
                ("municipio_emitente", models.CharField(blank=True, max_length=100)),
                ("uf_emitente", models.CharField(blank=True, max_length=2)),
                ("nome_destinatario", models.CharField(blank=True, max_length=255)),
                ("cnpj_destinatario", models.CharField(blank=True, max_length=14)),
                ("descricao_servico", models.TextField(blank=True)),
                (
                    "documento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados",
                        to="documentos.documento",
                    ),
                ),
            ],
        ),
    ]
